Repository WordPress/wporg-showcase-2022, pull requests merged in 2023-10, with the labels that each got.

#217 Add breadcrumbs to all pages
  source/wp-content/themes/wporg-showcase-2022/inc/block-config.php
  source/wp-content/themes/wporg-showcase-2022/patterns/_nav-dark.php
  source/wp-content/themes/wporg-showcase-2022/patterns/_nav.php
  source/wp-content/themes/wporg-showcase-2022/src/style/style.scss
  source/wp-content/themes/wporg-showcase-2022/templates/page-thanks.html
Labels: [Component] Theme

#228 Query Filters: Add taxonomy term counts
  source/wp-content/themes/wporg-showcase-2022/inc/block-config.php
Labels: [Component] Blocks/Editor, [Type] Enhancement

#239 Improve screen reader experience on site meta lists
  source/wp-content/themes/wporg-showcase-2022/src/site-meta-list/index.php
Labels: Accessibility

#245 Improve screen reader experience for site meta (v2)
  source/wp-content/themes/wporg-showcase-2022/src/site-meta-list/index.php
  source/wp-content/themes/wporg-showcase-2022/src/site-meta-list/style.scss
Labels: Accessibility

#249 Improve site meta list accessibility (V3)
  source/wp-content/themes/wporg-showcase-2022/src/site-meta-list/index.php
  source/wp-content/themes/wporg-showcase-2022/src/site-meta-list/style.scss
  source/wp-content/themes/wporg-showcase-2022/theme.json
Labels: Accessibility

#252 Revert "Query Filters: Add taxonomy term counts (#228)"
  source/wp-content/themes/wporg-showcase-2022/inc/block-config.php
Labels: [Component] Blocks/Editor, [Type] Enhancement

#253 Document meta: Improve the consistency of <title>s
  source/wp-content/themes/wporg-showcase-2022/functions.php
Labels: [Type] Enhancement, [Component] Content

#240 Fix dots pattern on mobile log in screen & thank you screen
  source/wp-content/themes/wporg-showcase-2022/patterns/log-in.php
  source/wp-content/themes/wporg-showcase-2022/src/style/style.scss
  source/wp-content/themes/wporg-showcase-2022/templates/page-log-in.html
  source/wp-content/themes/wporg-showcase-2022/templates/page-thanks.html
Labels: [Component] Theme, [Type] Bug

#254 Use chevron icon for local nav mobile menu
  source/wp-content/themes/wporg-showcase-2022/patterns/_nav-dark.php
  source/wp-content/themes/wporg-showcase-2022/patterns/_nav-front.php
  source/wp-content/themes/wporg-showcase-2022/patterns/_nav.php
Labels: [Component] Theme, [Type] Enhancement
