Repository WordPress/wporg-showcase-2022, pull requests merged in 2023-09, with the labels that each got.

#149 Add related sites to single site pages
  source/wp-content/themes/wporg-showcase-2022/functions.php
  source/wp-content/themes/wporg-showcase-2022/patterns/related-posts.php
  source/wp-content/themes/wporg-showcase-2022/src/style/_jetpack.scss
  source/wp-content/themes/wporg-showcase-2022/src/style/style.scss
  source/wp-content/themes/wporg-showcase-2022/templates/single.html
Labels: [Component] Theme

#152 Update submission flow
  source/wp-content/themes/wporg-showcase-2022/functions.php
  source/wp-content/themes/wporg-showcase-2022/images/dots-banner.svg
  source/wp-content/themes/wporg-showcase-2022/images/dots-dark-banner.svg
  source/wp-content/themes/wporg-showcase-2022/images/dots-red-banner.svg
  source/wp-content/themes/wporg-showcase-2022/images/star-blue.svg
  source/wp-content/themes/wporg-showcase-2022/images/star-red.svg
  source/wp-content/themes/wporg-showcase-2022/parts/page-submit-header.html
  source/wp-content/themes/wporg-showcase-2022/patterns/log-in.php
  source/wp-content/themes/wporg-showcase-2022/patterns/page-submit-auth.php
  source/wp-content/themes/wporg-showcase-2022/patterns/page-submit-confirmation.php
  source/wp-content/themes/wporg-showcase-2022/patterns/page-submit.php
  source/wp-content/themes/wporg-showcase-2022/src/style/_jetpack.scss
  source/wp-content/themes/wporg-showcase-2022/src/style/style.scss
  source/wp-content/themes/wporg-showcase-2022/templates/page-log-in.html
  source/wp-content/themes/wporg-showcase-2022/templates/page-submit-auth.html
  source/wp-content/themes/wporg-showcase-2022/templates/page-submit-confirmation.html
  source/wp-content/themes/wporg-showcase-2022/templates/page-submit.html
  source/wp-content/themes/wporg-showcase-2022/templates/page-thanks.html
  source/wp-content/themes/wporg-showcase-2022/theme.json
Labels: [Component] Site Submission

#172 Site screenshot: Load mshots images via JS, show CSS loading state
  source/wp-content/themes/wporg-showcase-2022/src/site-screenshot/block.json
  source/wp-content/themes/wporg-showcase-2022/src/site-screenshot/index.php
  source/wp-content/themes/wporg-showcase-2022/src/site-screenshot/render.php
  source/wp-content/themes/wporg-showcase-2022/src/site-screenshot/style.scss
  source/wp-content/themes/wporg-showcase-2022/src/site-screenshot/view.js
Labels: [Component] Blocks/Editor

#176 Footer: switch styling of footer CTA.
  source/wp-content/themes/wporg-showcase-2022/patterns/_footer.php
Labels: [Component] Theme

#175 Site screenshot: Add responsive image support to the screenshot block
  source/wp-content/themes/wporg-showcase-2022/functions.php
  source/wp-content/themes/wporg-showcase-2022/patterns/_site-grid-featured.php
  source/wp-content/themes/wporg-showcase-2022/patterns/_site-grid.php
  source/wp-content/themes/wporg-showcase-2022/patterns/_site-hero.php
  source/wp-content/themes/wporg-showcase-2022/patterns/screenshot-auditor.php
  source/wp-content/themes/wporg-showcase-2022/src/site-screenshot/block.json
  source/wp-content/themes/wporg-showcase-2022/src/site-screenshot/index.php
  source/wp-content/themes/wporg-showcase-2022/src/site-screenshot/readme.md
  source/wp-content/themes/wporg-showcase-2022/src/site-screenshot/render.php
  source/wp-content/themes/wporg-showcase-2022/src/style/style.scss
  source/wp-content/themes/wporg-showcase-2022/templates/single.html
Labels: [Component] Blocks/Editor

#204 Add more space between the dots spacer and content.
  source/wp-content/themes/wporg-showcase-2022/templates/page-browse.html
  source/wp-content/themes/wporg-showcase-2022/templates/single.html
Labels: [Component] Theme

#193 Archives: Update the main heading on all filter views
  source/wp-content/themes/wporg-showcase-2022/functions.php
  source/wp-content/themes/wporg-showcase-2022/inc/block-config.php
  source/wp-content/themes/wporg-showcase-2022/patterns/_site-grid.php
Labels: [Component] Blocks/Editor, Accessibility
